### ISSUE TITLE
Why does it sort my keys in alphabet order?

### ISSUE THREAD

**Issue by foreverLoveWisdom** [mk-fg/pretty-yaml#37]
I am using pyaml formatter with Neoformater in Neo Vim. 

This is my `docker-compose.yml` **before** formatting:
```
version: 3

services:
  web:
    build: .
    ports:
      - 3000:3000
```

**After** formatting:
```
services:
  web:
    build: .
    ports:
      - 3000:3000
version: 3
```
Is there a way for me to prevent it from ordering my keys in alphabet order?
